ALTER TABLE USUARIO ADD SITUACAO_BACKUP BIT NOT NULL;
UPDATE USUARIO SET SITUACAO_BACKUP = 0 WHERE SITUACAO = 'inativo';
UPDATE USUARIO SET SITUACAO_BACKUP = 1 WHERE SITUACAO = 'ativo';
UPDATE USUARIO SET SITUACAO = NULL;

ALTER TABLE USUARIO CHANGE COLUMN SITUACAO SITUACAO BIT;
UPDATE USUARIO SET SITUACAO = SITUACAO_BACKUP;

ALTER TABLE USUARIO DROP COLUMN SITUACAO_BACKUP;